export const SEED_TEAMS = {
  '12-blue': {
    name: '12 Blue', sub: 'Ages 12 & Under', division: 'Blue', color: 'blue',
    coaches: [{ name: 'Elise Bohl', title: 'Head Coach', bio: 'Experienced youth volleyball coach focused on fundamentals and player development at the 12U level.' }],
    practices: [
      { day: 'Tuesday',  time: '5:30 – 7:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Thursday', time: '5:30 – 7:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Skills & Fundamentals' },
      { day: 'Saturday', time: '9:00 – 11:00 AM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Open Gym / Extra Reps' },
    ],
    tournaments: [
      { date: '2026-02-14', endDate: '2026-02-15', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '25th place' },
    ],
    roster: [
      { name: 'Lillyan Bohl', num: 25, pos: '' },
      { name: 'Kelly Brell', num: 4, pos: '' },
      { name: 'Isla Day', num: 18, pos: '' },
      { name: 'Lauren Drew', num: 15, pos: '' },
      { name: 'Emma Freiburger', num: 11, pos: '' },
      { name: 'Delilah Quinn Nichter', num: 10, pos: '' },
      { name: 'Emma Pliett', num: 1, pos: '' },
      { name: 'Nellie Shaffer', num: 2, pos: '' },
    ],
  },
  '14-blue': {
    name: '14 Blue', sub: 'Ages 14 & Under', division: 'Blue', color: 'blue',
    coaches: [{ name: 'Elise Bohl', title: 'Head Coach', bio: 'Builds competitive 14U players through focused technical training and tournament preparation across Indiana.' }],
    practices: [
      { day: 'Tuesday',  time: '6:00 – 8:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Thursday', time: '6:45 – 8:45 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Position Training' },
    ],
    tournaments: [
      { date: '2026-01-17', endDate: '2026-01-18', name: "'26 Ft. Wayne MLK Challenge", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-01-31', endDate: '2026-02-01', name: 'Bloomington Invite', location: 'Advanced Event Systems', address: 'Bloomington, IN', result: '' },
      { date: '2026-02-14', endDate: '2026-02-15', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-02-28', endDate: '2026-03-01', name: 'South Shore Showdown', location: 'South Shore Convention', address: 'Hammond, IN', result: '' },
      { date: '2026-03-14', endDate: '2026-03-15', name: 'Freedom Classic', location: 'Brighton HS / Area', address: 'Brighton, MI', result: '' },
    ],
    roster: [
      { name: 'Londen Achenbach', num: 13, pos: '' },
      { name: 'Annabelle Bohl', num: 11, pos: '' },
      { name: 'Kayleen Burget', num: 7, pos: '' },
      { name: 'Victoria Collins', num: 5, pos: '' },
      { name: 'Alma Falk', num: 19, pos: '' },
      { name: 'Anastasia Falvaresi', num: 2, pos: '' },
      { name: 'Makenzie Holloway', num: 14, pos: '' },
      { name: 'Nora Lamont', num: 15, pos: '' },
      { name: 'Isabelle Mendez', num: 8, pos: '' },
      { name: 'Kaiea-Ikos Smith', num: 4, pos: '' },
    ],
  },
  '16-blue': {
    name: '16 Blue', sub: 'Ages 16 & Under', division: 'Blue', color: 'blue',
    coaches: [
      { name: 'Drew Achenbach', title: 'Head Coach', bio: 'Leads the 16 Blue program with a focus on offensive systems and competitive tournament play at regional and national levels.' },
      { name: 'Ainsley Kiefer', title: 'Assistant Coach', bio: 'Specializes in defensive training and libero development, bringing energy and technical expertise to the 16 Blue staff.' },
    ],
    practices: [
      { day: 'Monday',   time: '6:45 – 9:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Thursday', time: '6:45 – 8:45 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Offense & Defense' },
    ],
    tournaments: [
      { date: '2026-01-17', endDate: '2026-01-18', name: "'26 Ft. Wayne MLK Challenge", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-01-31', endDate: '2026-02-01', name: 'Clash at the Point', location: 'Advanced Event Systems', address: 'Sandusky, OH', result: '' },
      { date: '2026-02-14', endDate: '2026-02-15', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-03-07', endDate: '2026-03-08', name: 'Battle at the Border', location: 'Mishawaka HS / Area', address: 'Mishawaka, IN', result: '' },
      { date: '2026-04-18', endDate: '2026-04-19', name: 'Hoosier Invite', location: 'Fishers HS / Area', address: 'Fishers, IN', result: '' },
      { date: '2026-04-25', endDate: '2026-04-26', name: 'Lakeshore Volleyfest', location: 'Grand Rapids Area', address: 'Grand Rapids, MI', result: '' },
    ],
    roster: [
      { name: 'Noelle Achenbach', num: 0, pos: '' },
      { name: 'Taleece Fields', num: 0, pos: '' },
      { name: 'Jo Kinney', num: 0, pos: '' },
      { name: 'Eliza Kubly', num: 0, pos: '' },
      { name: 'Olivia Loya', num: 0, pos: '' },
      { name: 'Summer Sipfle', num: 0, pos: '' },
      { name: 'Claire Thompson', num: 0, pos: '' },
      { name: 'Taylor Thompson', num: 0, pos: '' },
    ],
  },
  '16-pink': {
    name: '16 Pink', sub: 'Ages 16 & Under', division: 'Pink', color: 'pink',
    coaches: [
      { name: 'Chana Drew', title: 'Head Coach', bio: "Passionate about building confident, competitive athletes. Chana brings a player-first philosophy and strong tactical knowledge to the 16 Pink team." },
      { name: 'Kyndal Pease', title: 'Assistant Coach', bio: 'Focuses on setter training and back-row development, helping 16 Pink athletes reach the next level of play.' },
    ],
    practices: [
      { day: 'Monday',  time: '6:45 – 9:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Tuesday', time: '6:00 – 8:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Serve & Pass' },
    ],
    tournaments: [
      { date: '2026-01-17', endDate: '2026-01-18', name: "'26 Ft. Wayne MLK Challenge", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '9th place' },
      { date: '2026-01-31', endDate: '2026-02-01', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '14th place' },
      { date: '2026-03-07', endDate: '2026-03-08', name: 'Battle at the Border', location: 'Mishawaka HS / Area', address: 'Mishawaka, IN', result: '14th place' },
    ],
    roster: [
      { name: 'Jasmine Bynaum', num: 3, pos: '' },
      { name: 'Mackenzie Clark', num: 2, pos: 'Middle Blocker' },
      { name: 'Sophia Fy', num: 5, pos: 'Def. Specialist' },
      { name: 'Isabelle Mendez', num: 8, pos: 'Def. Specialist' },
      { name: 'Layla Schmele', num: 37, pos: 'Setter / RS' },
      { name: 'Addie Snyder', num: 12, pos: 'Outside Hitter' },
      { name: 'Ella Schwarz', num: 7, pos: '' },
      { name: 'Isabelle Sheeler', num: 27, pos: '' },
      { name: 'Zoey Tanksley', num: 0, pos: '' },
    ],
  },
  '17-blue': {
    name: '17 Blue', sub: 'Ages 17 & Under', division: 'Blue', color: 'blue',
    coaches: [{ name: 'Kalah Baer', title: 'Head Coach', bio: 'Brings competitive club and collegiate playing experience to the 17 Blue program, with emphasis on elite skill development and championship-level mentality.' }],
    practices: [
      { day: 'Monday',   time: '6:45 – 9:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Thursday', time: '6:45 – 8:45 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Competition Prep' },
    ],
    tournaments: [
      { date: '2026-01-17', endDate: '2026-01-18', name: "'26 Ft. Wayne MLK Challenge", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-01-31', endDate: '2026-02-01', name: 'Clash at the Point', location: 'Advanced Event Systems', address: 'Sandusky, OH', result: '' },
      { date: '2026-02-14', endDate: '2026-02-15', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '' },
      { date: '2026-03-07', endDate: '2026-03-08', name: 'Battle at the Border', location: 'Mishawaka HS / Area', address: 'Mishawaka, IN', result: '' },
    ],
    roster: [
      { name: 'Taylor Albers', num: 7, pos: 'Outside Hitter' },
      { name: 'Isabella Beers', num: 5, pos: 'Outside Hitter' },
      { name: 'Sophia Crates', num: 44, pos: 'Def. Specialist' },
      { name: 'Reagan Eash', num: 3, pos: 'Middle Blocker' },
      { name: 'Caroline Hirschy', num: 8, pos: 'Def. Specialist' },
      { name: 'Kenedee Jameson', num: 16, pos: 'Setter' },
      { name: 'Sophia Kent', num: 14, pos: 'Outside Hitter' },
      { name: 'Brynlee McDougle', num: 6, pos: 'Middle / Outside' },
      { name: 'Olivia Roussey', num: 4, pos: 'Right Side / DS' },
      { name: 'Kaylin Slone', num: 1, pos: 'Setter' },
    ],
  },
  '18-blue': {
    name: '18 Blue', sub: 'Ages 18 & Under', division: 'Blue', color: 'blue',
    coaches: [
      { name: 'Naomi Willis', title: 'Head Coach', bio: 'Leads the flagship 18 Blue program with a record of developing players who go on to compete at the collegiate level.' },
      { name: 'Aaron Olsen', title: 'Assistant Coach', bio: 'Specializes in middle blocker and opposite development, with a background in high-level collegiate play.' },
    ],
    practices: [
      { day: 'Monday',  time: '6:45 – 9:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Full Team' },
      { day: 'Tuesday', time: '6:00 – 8:00 PM', location: 'Saint Aloysius School', address: '14623 Bluffton Rd, Yoder, IN', type: 'Competition Prep' },
    ],
    tournaments: [
      { date: '2026-01-17', endDate: '2026-01-18', name: "'26 Ft. Wayne MLK Challenge", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '19th place' },
      { date: '2026-02-14', endDate: '2026-02-15', name: "2026 President's Day", location: 'AllVolleyball.com Event', address: 'Fort Wayne, IN', result: '19th place' },
      { date: '2026-02-28', endDate: '2026-03-01', name: 'South Shore Showdown', location: 'South Shore Convention', address: 'Hammond, IN', result: '15th place' },
      { date: '2026-03-14', endDate: '2026-03-15', name: 'Freedom Classic', location: 'Brighton HS / Area', address: 'Brighton, MI', result: '8th place' },
    ],
    roster: [
      { name: 'Hadley Biddle Bruening', num: 24, pos: 'Def. Specialist', gradYear: '2027', school: 'Bishop Luers' },
      { name: 'Kyah Boots',             num: 17, pos: 'Def. Specialist', gradYear: '2027', school: 'Bluffton' },
      { name: 'MJ Brell',               num: 2,  pos: 'Setter',          gradYear: '2027', school: 'Bishop Luers' },
      { name: 'Suzannah Glowacki',      num: 13, pos: 'Middle Blocker',  gradYear: '2026', school: 'Homestead' },
      { name: 'Mady Priest',            num: 1,  pos: 'Outside Hitter',  gradYear: '2026', school: 'Snider' },
      { name: 'Alex Rahall',            num: 12, pos: 'Outside Hitter',  gradYear: '2026', school: 'Canterbury' },
      { name: 'Victoria Strack',        num: 8,  pos: 'Middle Blocker',  gradYear: '2026', school: 'Bishop Luers' },
      { name: 'Alexandra Vazquez',      num: 9,  pos: 'Libero',          gradYear: '2026', school: 'Bishop Luers' },
      { name: 'Jalayna Winebrenner',    num: 7,  pos: 'Setter',          gradYear: '2026', school: 'Central Noble' },
    ],
  },
};
